language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: MDZqc4QJlxH2YQ7wDa29emhTHd4DXPcniBrT17OWSFrN/Hg605VknGeQ5VQqRCXM8+Xi+NxDlBqGo1mh1iV+O5jxsZgCuFzhJ/GtkPhgM/Nyijcm7Ug6CfPdguRqGhOMD+zatPsq1P3K1QyNyGH/jDlWVsmpwSEv/mxp04RTQc5NA+OWGIXNaxA5/+QbVLp06tjxK6bGFrs+zp5uw4aO6IQd1Bo9PDmXinRQiKe4pv2dZGBBrNTTRcGt+hdzygt3ERpJ5Hjvf2FvpofyFP/jwMPdkbdc2Z1fviGCofhx8s9QmxdS0FNL6t/fxlhM6izzP1FO0VGIJ0FVPHasWJ/9t711W7TIOPf5IofnrnWIDNfY6awWy+5llAjTmsV11GkCXBhZlXRhBjk4cypsCMhlRZR2oIpZ0qAe8mI4I9h0kYl/tMzkQZBrGNmB8xXp1tp9Qon5MSXZpjxIl5+fEIXRTSwZ84jbMUyHg7SDnC7fimjs/akZVRlEoq3hY9zqG3OVbNsVWJUrLNT2GRAoxpMyYh5FDNl2gXcCHQqsWpzYYg1JoszLlPjuGDORmoAGG1vPBs+Tu5rzM2IEDab3dahjdhh0rMsKnWwVxhkyEQfKF4udrwxPqugq8pGbYUc9thxngPuhIyq43YeKvhNJ5NHwrL1mQDT/MWjZm0XQfIgnmtA=
  app: secure-falls-63627
  on:
    repo: Laurn17/https-github.com-Thinkful-Ed-node-shopping-list-integration-tests
